---
title: "growth_analysis_clean"
output: html_document
date: "2026-04-15"
editor_options: 
  chunk_output_type: console
---

# library
```{r}
library(tidyverse)
library(arrow)
library(ggplot2)
library(dplyr)
library(sf)
library(ggspatial)
library(ggthemes)
library(rnaturalearth)
library(rnaturalearthdata)
library(leaflet)
library(brms)
library(tidybayes)
library(mwlaxeref)
#speeds up model fitting
library(cmdstanr)
options(brms.backend = "cmdstanr")
```

# data
```{r}
#reading in the updated Minnesota data
mn_data <- open_dataset(sources = file.path("D:",
                                            "Shared drives",
                                            "Hansen Lab",
                                            "RESEARCH PROJECTS",
                                            "Fish Survey Data",
                                            "Parquet files",
                                            "mn_update")) %>% 
  filter(state == "Minnesota" & !is.na(est_age))

zm_ssw <- read_csv(file.path("D:",
                             "Shared drives",
                             "Hansen Lab",
                             "RESEARCH PROJECTS",
                             "MAISRC Mercury Pathways 53.2",
                             "Data",
                             "zm_ssw_6jan2026.csv")) %>% 
  #filter out na dows or those "none"
  filter(!is.na(dow) & !(str_detect(dow, "n"))) %>% 
  #generate original id for reference
  mutate(original_id = dow) %>% 
  #remove dashes
  #make sure short dows are 8 digits
  #fix a few manually
  #remove leading 0s to match the fish data
  mutate(dow = str_replace_all(dow, pattern = "-", ""),
         dow = if_else(nchar(dow) == 6, paste0(dow, "00"), dow),
         dow = case_when(dow == "10179" ~ "01017900",
                         str_detect(dow, "040063") ~ "04006300",
                         TRUE ~ dow),
         dow = case_when(str_starts(dow, "0") ~ str_sub(dow, 2),
                         TRUE ~ dow))  %>% 
  #rename dow to match fishereis column
  rename(lake_id = dow) %>% 
  #pivot to lake per row, with zm and starry columns 
  pivot_wider(id_cols = c(lake_id, lake_name),
              names_from = ais,
              values_from = year_infested,
              values_fn = min) %>% 
  rename(zm = `zebra mussel`,
         ssw = `starry stonewort`)

#crosswalk - get lat and lon from fish data
xwalk <- open_dataset(sources = file.path("D:",
                                            "Shared drives",
                                            "Hansen Lab",
                                            "RESEARCH PROJECTS",
                                            "Fish Survey Data",
                                            "Parquet files",
                                            "mn_update")) %>% 
  select(state, latitude_lake_centroid, lake_id, longitude_lake_centroid) %>% 
  filter(state == "Minnesota") %>% 
  filter(!is.na(latitude_lake_centroid) & !is.na(lake_id)) %>% 
  distinct(lake_id, latitude_lake_centroid, longitude_lake_centroid) %>% 
  collect()

gdd <- read_feather(file.path("D:",
                              "Shared drives",
                              "Hansen Lab",
                              "RESEARCH PROJECTS",
                              "MAISRC Mercury Pathways 53.2",
                              "Data",
                              "lake_temperature_metrics_GLM_NLDAS.feather")) %>% 
  select(site_id,
         year,
         gdd_wtr_5c) %>% 
  #get DOW from NHDHR
  mutate(site_id = str_remove(site_id, "nhdhr_")) %>% 
  nhdhr_to_local(from_colname = "site_id",states = "mn") %>% 
  #need to drop leading 0 to match fish data - then convert back to char
  mutate(lake_id = as.numeric(local.id),
         lake_id = as.character(lake_id)) %>% 
  distinct(lake_id, year, gdd_wtr_5c)
glimpse(gdd)

gdd <- gdd %>% 
  group_by(lake_id) %>% 
  mutate(lake_avg_gdd = mean(gdd_wtr_5c),
         gdd_anom = gdd_wtr_5c - lake_avg_gdd) %>% 
  ungroup()
```

# Inventory of sample size with varying filtering
```{r}
age_data <- mn_data %>% 
  #filter MN data for fish with alked year level data
  filter(alk == "year") %>% 
  left_join(zm_ssw, by = "lake_id") %>% 
  select(lake_id,
         nhdhr_id,
         date_total_effort_ident,
         date_sample,
         year,
         sampling_method,
         site_id,
         species_1,
         length_1,
         length_unit_1,
         age,
         aging_structure_1,
         sex,
         est_age,
         alk,
         alk_age_str,
         alk_length,
         alk_n,
         weight_1,
         weight_unit_1,
         flag,
         notes_1,
         zm) %>% 
  collect() 

#################ALK exploration##############################################
age_data %>% 
  summarise(n_spec_lake_years = n_distinct(species_1, year, lake_id),
            n_spec_lake = n_distinct(species_1, lake_id),
            n_lake = n_distinct(lake_id))
  

age_data %>% 
  group_by(lake_id) %>% 
  summarise(n_spec = n_distinct(species_1)) %>%
  summarise(mean_n_species = mean(n_spec),
            median_n_species = median(n_spec))
  

age_data %>% 
  group_by(lake_id) %>% 
  summarise(n_spec_years = n_distinct(species_1, year)) %>%
  summarise(mean_n_species = mean(n_spec_years),
            median_n_species = median(n_spec_years))

age_data %>% 
  distinct(lake_id, species_1, year, alk_age_str) %>% 
  group_by(alk_age_str) %>% 
  summarise(n = n(),
            prop = n/4415,
            percent = prop*100)


age_data %>%
  distinct(lake_id, species_1, year, alk_age_str) %>%
  count(species_1, year, alk_age_str, name = "n") %>%
  group_by(species_1, year) %>%
  complete(alk_age_str, fill = list(n = 0)) %>%
  mutate(prop = n / sum(n)) %>%
  ungroup() %>% 
  ggplot(aes(year, prop, color = alk_age_str)) +
  geom_line(linewidth = 1) +
  facet_wrap(~ species_1) +
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Proportion", x = "Year", color = "Age Str") +
  theme(legend.position = c(.8, .1))
#ggsave("prop_alk_str.jpg", height = 5, width = 7)

age_data %>% 
  distinct(lake_id, year, alk_age_str) %>%
  filter(year > 2020 & alk_age_str == "scale") %>% 
  group_by(lake_id) %>% 
  count()

age_data %>%
  filter(alk_age_str == "scale") %>%
  filter(!is.na(aging_structure_1)) %>%
  distinct(lake_id, year, species_1, aging_structure_1) %>%
  group_by(lake_id, year, species_1) %>%
  summarise(
    structures = paste(sort(aging_structure_1), collapse = ", "),
    .groups = "drop"
  ) %>%
  count(structures, sort = TRUE) %>% 
  mutate(n_total = sum(n),
         prop = n/n_total) %>% 
  print(n = nrow(.))
##############################################################################
age_data %>% 
  filter(!is.na(zm)) %>% 
  summarise(n_distinct(lake_id),
            n_distinct(lake_id, species_1),
            n_distinct(lake_id, species_1, year))

age_data %>% 
  filter(!is.na(zm)) %>% 
  distinct(lake_id, species_1, year, alk_age_str) %>% 
  group_by(alk_age_str) %>% 
  summarise(n = n()) %>% 
  mutate(prop = n/sum(n),
         percent = prop*100)

exposure_summary <- age_data %>%
  filter(!is.na(zm)) %>%
  mutate(
    birth_year = year - est_age,
    exposure = case_when(
      year < zm ~ "before",
      birth_year >= zm ~ "after",
      TRUE ~ "mixed"
    )
  ) %>%
  group_by(lake_id, species_1, exposure) %>%
  summarise(n_years = n_distinct(year), .groups = "drop") %>%
  group_by(lake_id, species_1) %>%
  summarise(
    exposure_combo = paste(sort(exposure), collapse = " + "),
    .groups = "drop"
  )


exposure_summary %>% 
  group_by(species_1, exposure_combo) %>% 
  summarise(lakes = n()) %>% 
ggplot(aes(x = exposure_combo, y = species_1, fill = lakes)
) +
  geom_tile(alpha = .5,show.legend = F) +
  geom_text(aes(label = lakes), size = 4) +
  labs(
    x = NULL,
    y = NULL
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(
      angle = 30,
      hjust = 1,
      vjust = 1
    )
  )
#ggsave("heat_map_zm_lakes.jpg", height = 5, width = 7)
rm(exposure_summary)

age_data %>%
  filter(!is.na(zm)) %>%
  mutate(
    birth_year = year - est_age,
    exposure = case_when(
      year < zm ~ "before",
      birth_year >= zm ~ "after",
      TRUE ~ "mixed"
    )
  ) %>%
  distinct(lake_id, species_1, exposure) %>%
  group_by(lake_id, species_1) %>%
  summarise(
    has_before = "before" %in% exposure,
    has_after = "after" %in% exposure,
    .groups = "drop"
  ) %>%
  filter(has_before & has_after) %>%
  count(species_1, name = "n_lakes") %>% 
  arrange(desc(n_lakes))

age_data %>%
  filter(!is.na(zm)) %>%
  mutate(
    birth_year = year - est_age,
    exposure = case_when(
      year < (zm + 2) ~ "before",
      birth_year >= (zm + 2) ~ "after",
      TRUE ~ "mixed"
    )
  ) %>%
  distinct(lake_id, species_1, exposure) %>%
  group_by(lake_id, species_1) %>%
  summarise(
    has_before = "before" %in% exposure,
    has_after = "after" %in% exposure,
    .groups = "drop"
  ) %>%
  filter(has_before & has_after) %>%
  count(species_1, name = "n_lakes") %>% 
  arrange(desc(n_lakes))

#before and after lakes 
valid_groups <- age_data %>% 
  mutate(
    birth_year = year - est_age,
    exposure = case_when(
      year < zm ~ "before",
      birth_year >= zm ~ "after",
      TRUE ~ "mixed"
    )
  ) %>%
  group_by(lake_id, species_1) %>% 
  summarise(
    has_before = any(exposure == "before"),
    has_after  = any(exposure == "after"),
    .groups = "drop"
  ) %>% 
  filter(
    has_before,
    has_after
  )

age_data_filtered <- age_data %>% 
  semi_join(valid_groups, by = c("lake_id", "species_1"))

age_check <- age_data_filtered %>%
  group_by(lake_id, year, species_1) %>%
  mutate(
    birth_year = year - est_age,
    exposure = case_when(
      year < zm ~ "before",
      birth_year >= zm ~ "after",
      TRUE ~ "mixed"
    )
  ) %>% 
  summarise(
    n_ages_before = n_distinct(est_age[exposure == "before" & !is.na(est_age)]),
    n_ages_after  = n_distinct(est_age[exposure == "after"  & !is.na(est_age)]),
    #.groups = "drop"
  ) 

age_check %>%
  pivot_longer(
    cols = c(n_ages_before, n_ages_after),
    values_to = "n",
    names_to = "exposure"
  ) %>%
  ggplot(aes(n, fill = exposure)) +
  geom_histogram(
    position = "dodge",
    binwidth = 1,
    #color = "black"
  ) +
  geom_vline(xintercept = 5) +
  facet_wrap(~species_1) +
  theme_bw() +
  theme(legend.position = c(.83, 0.1))
#ggsave("unique_ages_before_after.jpg", height = 5, width = 5)

glimpse(age_check)

#now lets filter so that we get lake years with before and after that have at least 5 age groupings
lakes_5 <- age_check %>% 
  group_by(lake_id, species_1) %>% 
   summarise(
    has_before_5 = any(n_ages_before >= 5),
    has_after_5  = any(n_ages_after >= 5),
    .groups = "drop"
  ) %>% 
  filter(has_before_5, has_after_5)

lakes_5 %>% 
  count(species_1, name = "n_lakes")
  
age_data_filtered <- age_data %>% 
  semi_join(lakes_5, by = c("lake_id", "species_1")) %>% 
  group_by(lake_id, year, species_1) %>%
  mutate(
    birth_year = year - est_age,
    exposure = case_when(
      year < zm ~ "before",
      birth_year >= zm ~ "after",
      TRUE ~ "mixed"
    )
  ) 

age_data_filtered %>% 
  ungroup() %>% 
  summarise(n_distinct(lake_id, species_1))

age_data_filtered %>% 
  group_by(species_1, exposure, est_age) %>% 
  summarise(n_lakes = n_distinct(lake_id)) %>% 
  left_join(age_data_filtered %>% 
              group_by(species_1) %>% 
              summarise(total_lakes = n_distinct(lake_id), .groups = "drop"),
                        by = c("species_1")) %>% 
              mutate(prop_lakes = n_lakes/ total_lakes) %>% 
  filter(exposure != "mixed") %>% 
  ggplot() +
  geom_tile(aes(est_age, exposure, fill = prop_lakes)) +
  facet_wrap(~species_1, scales = "free_x") +
  theme(legend.position = c(0.83, 0.1))
#ggsave("heat_ages_spec.jpg", height = 5, width = 7)

target_ages <- tibble::tribble(
  ~species_1,        ~est_age,
  "walleye",          1,
  "walleye",          2,
  "walleye",          3,
  "walleye",          4,
  "walleye",          5,
  "northern_pike",    1,
  "northern_pike",    2,
  "northern_pike",    3,
  "northern_pike",    4,
  "northern_pike",    5,
  "bluegill",         2,
  "bluegill",         3,
  "bluegill",         4,
  "bluegill",         5,
  "bluegill",         6)

qualified_years <- age_data_filtered %>%
  distinct(lake_id, year, species_1, exposure, est_age) %>%
  inner_join(target_ages,
             by = c("species_1", "est_age")) %>%
  count(lake_id, year, species_1, exposure,
        name = "n_target_ages") %>% 
  filter(exposure != "mixed" & n_target_ages == 5) %>% 
  group_by(lake_id, species_1) %>% 
  summarise(has_before = any(exposure == "before"),
            has_after = any(exposure == "after"),
            .groups = "drop") %>% 
  filter(has_before, has_after)

qualified_years %>% 
  group_by(species_1) %>% 
  count()
rm(valid_groups, target_ages, lake_age_summary, age_check)

aging_changes <- age_data_filtered %>%
  semi_join(qualified_years, by = c("lake_id", "species_1")) %>%
  filter(exposure != "mixed") %>%
  distinct(lake_id, species_1, exposure, alk_age_str) %>%
  group_by(lake_id, species_1, exposure) %>%
  summarise(
    structures = paste(sort(unique(alk_age_str)), collapse = ", "),
    .groups = "drop"
  ) %>%
  tidyr::pivot_wider(
    names_from = exposure,
    values_from = structures
  ) %>%
  mutate(
    changed = before != after
  )

aging_changes %>%
  count(species_1, changed)

aging_changes %>%
  count(species_1, before, after, sort = TRUE)

ggplot(aging_changes %>% 
         group_by(species_1, before, after) %>% 
         count(),
       aes(before, after, fill = n)) +
  geom_tile() +
  scale_fill_gradient(low = "gray", high = "white") +
  geom_text(aes(label = n)) +
  facet_wrap(~species_1, scales = "free") +
  theme_bw() +
   theme(
    axis.text.x = element_text(
      angle = 30,
      hjust = 1,
      vjust = 1
    ),
    legend.position = "none"
  )
#ggsave("heat_pre_post_str.jpg", height = 5, width = 7)
rm(aging_changes)

#how many years past 2021 do we have and how would that change n lakes?
gdd_check <- age_data_filtered %>%
  ungroup() %>% 
  semi_join(qualified_years, by = c("lake_id", "species_1")) %>%
  filter(exposure != "mixed") 

gdd_check %>% 
  distinct(lake_id, species_1, exposure, year) %>% 
  filter(year <= 2021) %>% 
  group_by(lake_id, species_1) %>% 
  summarise(has_before = any(exposure == "before"),
            has_after = any(exposure == "after"),
            .groups = "drop") %>% 
  filter(has_before, has_after) %>% 
  group_by(species_1) %>% 
  count()

gdd_check %>% 
  filter(year <= 2021) %>% 
  distinct(lake_id, species_1, exposure, year, zm) %>% 
  group_by(lake_id, species_1, exposure, zm) %>% 
  summarise(max_year = max(year)) %>% 
  mutate(zm_lag = zm + 2) %>% 
  filter(exposure == "after") %>% 
  summarise(n_lag_cut = (zm_lag >= max_year)) %>% 
  group_by(species_1, n_lag_cut) %>% 
  count()

gdd_check %>% 
  filter(year <= 2021) %>% 
  distinct(lake_id, species_1, exposure, year, zm) %>% 
  group_by(lake_id, species_1, exposure, zm) %>% 
  summarise(max_year = max(year)) %>% 
  mutate(zm_lag = zm + 2) %>% 
  filter(exposure == "after") %>% 
  print(n = nrow(.))


age_data_filtered %>% 
  filter(lake_id == "61013000" & species_1 == "walleye") %>% 
  group_by(year, exposure, est_age) %>% 
  count() %>% 
  print(n = nrow(.))

glimpse(gdd)
gdd %>% 
  filter(lake_id == "11041500")
rm(gdd_check)

#############################################################################
age_data_zm <- age_data %>% 
  filter(!is.na(zm)) %>% 
  mutate(
    birth_year = year - est_age,
    exposure = case_when(
      year < zm ~ "before",
      birth_year >= zm ~ "after",
      TRUE ~ "mixed"
    )
  ) %>% 
  filter(exposure == "after") %>% 
  ungroup()
glimpse(age_data_zm)

age_data_zm %>% 
  group_by(species_1, est_age) %>% 
  summarise(n_lakes = n_distinct(lake_id)) %>% 
  ggplot() +
  geom_line(aes(est_age, n_lakes)) +
  geom_line(data = age_data_zm %>% 
              filter(alk_age_str == "otolith") %>% 
              group_by(species_1, est_age) %>% 
              summarise(n_lakes = n_distinct(lake_id)), aes(est_age, n_lakes), color = "red") +
  geom_point(aes(est_age, n_lakes)) +
  facet_wrap(~species_1, scales = "free_y") +
  theme_bw()

age_data_zm  %>% 
  distinct(lake_id, species_1, zm, year) %>% 
  mutate(timing = year - zm) %>% 
  ggplot() +
  geom_histogram(aes(timing),binwidth = 1) +
  geom_vline(xintercept = 5) +
  facet_wrap(~species_1)

age_data_zm  %>% 
  distinct(lake_id, species_1, zm, year) %>% 
  summarise(n_lake_years = n_distinct(lake_id, species_1, years))

age_data_zm  %>% 
  distinct(lake_id, species_1, zm, year) %>% 
  summarise(n_lake_years = n_distinct(lake_id))

age_data_zm %>% 
  distinct(lake_id, species_1, year) %>% 
  group_by(lake_id, species_1) %>% 
  summarise(n_years = n()) %>% 
  ggplot() +
  geom_histogram(aes(n_years), binwidth = 1) +
  facet_wrap(~species_1)

age_data_zm %>% 
  distinct(lake_id, species_1, year) %>% 
  group_by(lake_id, species_1) %>% 
  summarise(n_years = n()) %>% 
  group_by(species_1) %>% 
  summarise(min = min(n_years),
            mean = mean(n_years),
            median = median(n_years),
            max = max(n_years),
            n = n())

age_data_zm %>% 
  distinct(lake_id, species_1, year) %>% 
  group_by(lake_id, species_1) %>% 
  summarise(n_years = n()) %>% 
  group_by(species_1) %>% 
  summarise(n_1_year = sum(n_years == 1),
            n = n()) %>% 
  mutate(prop_1 = n_1_year/n)
```


# filter for analysis 
```{r}
age_data <- mn_data %>% 
  #filter MN data for fish with alked year level data
  filter(alk == "year") %>% 
  left_join(zm_ssw, by = "lake_id") %>% 
  select(lake_id,
         nhdhr_id,
         date_total_effort_ident,
         date_sample,
         year,
         sampling_method,
         site_id,
         species_1,
         length_1,
         length_unit_1,
         age,
         aging_structure_1,
         sex,
         est_age,
         alk,
         alk_age_str,
         alk_length,
         alk_n,
         weight_1,
         weight_unit_1,
         flag,
         notes_1,
         zm) %>% 
  collect() %>% 
  #only take zebra mussel lakes
  filter(!is.na(zm)) %>% 
  #make timing columns
  mutate(zm_lag = zm+2,
         birth_year = year - est_age,
         exposure = case_when(
           year < zm_lag ~ "before",
           birth_year >= zm_lag ~ "after",
           TRUE ~ "drop"
         )) %>% 
  #remove mix fish
  filter(exposure != "drop")

#add in gdd 
age_data <- age_data %>% 
  mutate(fish_id = row_number())

fish_years <- age_data %>% 
  mutate(alive_year = map2(birth_year, year, seq)) %>% 
  unnest(alive_year)

fish_years <- fish_years %>% 
  left_join(gdd,
            by = c("lake_id",
                   "alive_year" = "year"))

thermal_history <- fish_years %>% 
  group_by(fish_id) %>% 
  summarise(lifetime_gdd_anom = sum(gdd_anom))

age_data <- age_data %>% 
  left_join(thermal_history,
            by = "fish_id")
rm(fish_years, thermal_history, gdd)

#filtering for valid groups
valid_groups <- age_data %>% 
  group_by(lake_id, species_1) %>% 
  summarise(
    has_before = any(exposure == "before"),
    has_after  = any(exposure == "after"),
    
    has_gdd_before = any(exposure == "before" &
                           !is.na(lifetime_gdd_anom)),
    
    has_gdd_after  = any(exposure == "after" &
                           !is.na(lifetime_gdd_anom)),
    
    .groups = "drop"
  ) %>% 
  filter(
    has_before,
    has_after,
    has_gdd_before,
    has_gdd_after
  )

#gather fish that have before and after data
age_data_filtered <- age_data %>% 
  semi_join(valid_groups, by = c("lake_id", "species_1"))


# now lets filter for a minimum number of unique age classes within each group
age_check <- age_data_filtered %>%
  group_by(lake_id, species_1) %>%
  summarise(
    n_ages_before = n_distinct(est_age[exposure == "before" & !is.na(est_age)]),
    n_ages_after  = n_distinct(est_age[exposure == "after"  & !is.na(est_age)]),
    .groups = "drop"
  ) %>%
  filter(n_ages_before >= 5, n_ages_after >= 5)

age_data_filtered <- age_data_filtered %>% 
  semi_join(age_check, by = c("lake_id", "species_1"))

#quick check
check <- age_data_filtered %>% 
  group_by(lake_id, species_1) %>% 
  summarise(n_fish_before = sum(exposure == "before"),
            n_fish_after = sum(exposure == "after"),
            n_ages_before = n_distinct(est_age[exposure == "before"]),
            n_ages_after = n_distinct(est_age[exposure == "after"]))
rm(check, age_check, age_data, valid_groups)
#we see here that all lake-species-exposure have at least five different ages

#now create objects for each species 
species_list <- split(age_data_filtered, age_data_filtered$species_1)
```

# model wae
```{r}
#lets walleye first
wae <- species_list[["walleye"]]

wae <- wae %>% 
  filter(!is.na(lifetime_gdd_anom))

#make sure we only used common ages across lakes
#first we look at ages that are the same in both exposures in each lake
ages_within_lake <- wae %>%
  group_by(lake_id, est_age) %>%
  summarise(
    has_before = any(exposure == "before"),
    has_after  = any(exposure == "after"),
    .groups = "drop"
  ) %>%
  filter(has_before & has_after)

#now look at ages across all lakes
ages_global <- ages_within_lake %>%
  group_by(est_age) %>%
  summarise(
    n_lakes = n_distinct(lake_id),
    .groups = "drop"
  )
#looks reasonable to keep ages 1:5 (throws out a few lakes but maximizes est_ages and # of lakes)

required_ages <- 1:5

valid_lakes <- wae %>%
  filter(est_age %in% required_ages) %>%
  group_by(lake_id, exposure) %>%
  summarise(
    n_ages = n_distinct(est_age),
    min_age = min(est_age),
    max_age = max(est_age),
    .groups = "drop"
  ) %>% 
  filter(n_ages == 5, min_age == 1, max_age == 5) %>% 
  group_by(lake_id) %>%
  filter(n_distinct(exposure) == 2) %>% 
  distinct(lake_id) %>% 
  pull(lake_id) 

wae_filtered <- wae %>%
  filter(lake_id %in% valid_lakes,
         est_age %in% required_ages)

wae_filtered %>% 
  group_by(lake_id, exposure) %>% 
  summarise(n_ages =  n_distinct(est_age),
            min = min(est_age),
            max = max(est_age),
            n = n()) %>% 
  print(n = nrow(.))

wae_filtered %>% 
  group_by(lake_id) %>% 
  summarise(n = n_distinct(exposure))

wae_filtered %>% 
  filter(!is.na(lifetime_gdd_anom)) %>% 
  group_by(lake_id) %>% 
  summarise(n_invasion = n_distinct(exposure))

rm(ages_global,
   ages_within_lake,
   required_ages,
   valid_lakes)

#Pepin does not relate to this analysis
wae_filtered <- wae_filtered %>% 
  filter(lake_id != "25000100")

gdd_anom_mean <- mean(wae_filtered$lifetime_gdd_anom)
gdd_anom_sd <- sd(wae_filtered$lifetime_gdd_anom)

wae_filtered <- wae_filtered %>% 
  mutate(est_age = as.factor(est_age),
         sc_lifetime_gdd_anom = (lifetime_gdd_anom - gdd_anom_mean)/gdd_anom_sd)

wae_plot <- wae_filtered %>% 
  group_by(lake_id, est_age, exposure) %>% 
  summarise(n = n(), .groups = "drop") %>% 
  group_by(lake_id) %>% 
  mutate(total_n = sum(n)) %>% 
  ungroup()

wae_plot %>% 
  ggplot(aes(
    x = factor(est_age), 
    y = n, 
    fill = fct_reorder(lake_id, total_n)
  )) +
  geom_col(position = "fill") +
  labs(x = "Estimated Age", y = "Proportion", fill = "Lake") +
  facet_wrap(~exposure)

wae_filtered %>%
  mutate(est_age = as.integer(est_age)) %>% 
  ggplot() +
  geom_point(aes(sc_lifetime_gdd_anom, length_1, color = lake_id)) +
  geom_smooth(aes(sc_lifetime_gdd_anom, length_1, color = lake_id), method = "lm") +
  facet_wrap(~est_age)

wae_filtered %>% 
  filter(!is.na(age)) %>% 
  group_by(lake_id, exposure, aging_structure_1) %>% 
  count() %>% 
  arrange(lake_id) %>% 
  print(n = nrow(.))

#fit model
fit_wae <- brm(
  length_1 ~ est_age * exposure + sc_lifetime_gdd_anom 
    + (1 + exposure | lake_id),
  data = wae_filtered,
  family = gaussian(),
  chains = 4,
  iter = 4000,
  warmup = 1000,
  cores = 4,
  backend = "cmdstanr",
  threads = threading(2), 
  control = list(
    adapt_delta = 0.95,
    max_treedepth = 12))

saveRDS(fit_wae, file.path("G:",
                          "Shared drives",
                          "Hansen Lab",
                          "RESEARCH PROJECTS",
                          "MAISRC Mercury Pathways 53.2",
                          "Growth Analysis",
                          "length_mean_ages_wae.rds"))
rm(wae_plot, wae, wae_filtered)
```

# model nop
```{r}
nop <- species_list[["northern_pike"]]

nop <- nop %>% 
  filter(!is.na(lifetime_gdd_anom))

#make sure we only used common ages across lakes
#first we look at ages that are the same in both exposures in each lake
ages_within_lake <- nop %>%
  group_by(lake_id, est_age) %>%
  summarise(
    has_before = any(exposure == "before"),
    has_after  = any(exposure == "after"),
    .groups = "drop"
  ) %>%
  filter(has_before & has_after)

#now look at ages across all lakes
ages_global <- ages_within_lake %>%
  group_by(est_age) %>%
  summarise(
    n_lakes = n_distinct(lake_id),
    .groups = "drop"
  )
#looks reasonable to keep ages 1:5 (throws out a few lakes but maximizes est_ages and # of lakes)

required_ages <- 1:5

valid_lakes <- nop %>%
  filter(est_age %in% required_ages) %>%
  group_by(lake_id, exposure) %>%
  summarise(
    n_ages = n_distinct(est_age),
    min_age = min(est_age),
    max_age = max(est_age),
    .groups = "drop"
  ) %>% 
  filter(n_ages == 5, min_age == 1, max_age == 5) %>% 
  group_by(lake_id) %>%
  filter(n_distinct(exposure) == 2) %>% 
  distinct(lake_id) %>% 
  pull(lake_id) 

nop_filtered <- nop %>%
  filter(lake_id %in% valid_lakes,
         est_age %in% required_ages)

nop_filtered %>% 
  group_by(lake_id, exposure) %>% 
  summarise(n_ages =  n_distinct(est_age),
            min = min(est_age),
            max = max(est_age)) %>% 
  print(n = nrow(.))

nop_filtered %>% 
  group_by(lake_id) %>% 
  summarise(n_invasion = n_distinct(exposure))

rm(ages_global,
   ages_within_lake,
   required_ages,
   valid_lakes)

gdd_mean_anom <- mean(nop_filtered$lifetime_gdd_anom)
gdd_sd_anom <- sd(nop_filtered$lifetime_gdd_anom)

nop_filtered <- nop_filtered %>% 
  mutate(est_age = as.factor(est_age),
         sc_lifetime_gdd_anom = (lifetime_gdd_anom - gdd_mean_anom)/gdd_sd_anom)

nop_plot <- nop_filtered %>% 
  group_by(lake_id, est_age, exposure) %>% 
  summarise(n = n(), .groups = "drop") %>% 
  group_by(lake_id) %>% 
  mutate(total_n = sum(n)) %>% 
  ungroup()

nop_plot %>% 
  ggplot(aes(
    x = factor(est_age), 
    y = n, 
    fill = fct_reorder(lake_id, total_n)
  )) +
  geom_col(position = "fill") +
  labs(x = "Estimated Age", y = "Proportion", fill = "Lake") +
  facet_wrap(~exposure)


#fit model
fit_nop <- brm(
  length_1 ~ est_age * exposure + sc_lifetime_gdd_anom + (1 | lake_id),
  data = nop_filtered,
  family = gaussian(),
  chains = 4,
  iter = 4000,
  warmup = 1000,
  cores = 4,
  backend = "cmdstanr",
  threads = threading(4), 
  control = list(
    adapt_delta = 0.95,
    max_treedepth = 12))

saveRDS(fit_nop, file.path("G:",
                          "Shared drives",
                          "Hansen Lab",
                          "RESEARCH PROJECTS",
                          "MAISRC Mercury Pathways 53.2",
                          "Growth Analysis",
                          "length_mean_ages_nop.rds"))

rm(nop, nop_filtered, nop_plot)
```

# model blg
```{r}
blg <- species_list[["bluegill"]]

blg <- blg %>% 
  filter(!is.na(lifetime_gdd_anom))

#make sure we only used common ages across lakes
#first we look at ages that are the same in both exposures in each lake
ages_within_lake <- blg %>%
  group_by(lake_id, est_age) %>%
  summarise(
    has_before = any(exposure == "before"),
    has_after  = any(exposure == "after"),
    .groups = "drop"
  ) %>%
  filter(has_before & has_after)

#now look at ages across all lakes
ages_global <- ages_within_lake %>%
  group_by(est_age) %>%
  summarise(
    n_lakes = n_distinct(lake_id),
    .groups = "drop"
  )

required_ages <- 2:6

valid_lakes <- blg %>%
  filter(est_age %in% required_ages) %>%
  group_by(lake_id, exposure) %>%
  summarise(
    n_ages = n_distinct(est_age),
    min_age = min(est_age),
    max_age = max(est_age),
    .groups = "drop"
  ) %>% 
  filter(n_ages == 5, min_age == 2, max_age == 6) %>% 
  group_by(lake_id) %>%
  filter(n_distinct(exposure) == 2) %>% 
  distinct(lake_id) %>% 
  pull(lake_id) 

blg_filtered <- blg %>%
  filter(lake_id %in% valid_lakes,
         est_age %in% required_ages) 

blg_filtered %>% 
  group_by(lake_id, exposure) %>% 
  summarise(n_ages =  n_distinct(est_age),
            min = min(est_age),
            max = max(est_age)) %>% 
  print(n = nrow(.))

rm(ages_global,
   ages_within_lake,
   required_ages,
   valid_lakes)

gdd_mean_anom <- mean(blg_filtered$lifetime_gdd_anom)
gdd_sd_anom <- sd(blg_filtered$lifetime_gdd_anom)

blg_filtered <- blg_filtered %>% 
  mutate(est_age = as.factor(est_age),
         sc_lifetime_gdd_anom = (lifetime_gdd_anom - gdd_mean_anom)/gdd_sd_anom) 

blg_plot <- blg_filtered %>% 
  group_by(lake_id, est_age,exposure) %>% 
  summarise(n = n(), .groups = "drop") %>% 
  group_by(lake_id) %>% 
  mutate(total_n = sum(n)) %>% 
  ungroup()

blg_plot %>% 
  ggplot(aes(
    x = factor(est_age), 
    y = n, 
    fill = fct_reorder(lake_id, total_n)
  )) +
  geom_col(position = "fill") +
  labs(x = "Estimated Age", y = "Proportion", fill = "Lake") +
  facet_wrap(~exposure)

blg_filtered %>%
  mutate(est_age = as.factor(est_age)) %>% 
  ggplot() +
  geom_point(aes(sc_lifetime_gdd_anom, length_1, color = lake_id)) +
  geom_smooth(aes(sc_lifetime_gdd_anom, length_1, color = lake_id), method = "lm") +
  geom_smooth(aes(sc_lifetime_gdd_anom, length_1), method = "lm", color = "black") +
  facet_wrap(~est_age)

blg_filtered %>%
  mutate(hatch_year = year - as.numeric(est_age)) %>%
  ggplot(aes(hatch_year,
             sc_lifetime_gdd_anom,
             color = factor(est_age))) +
  geom_point() +
  geom_smooth(se = FALSE)

blg_filtered %>% 
  filter(!is.na(age)) %>% 
  group_by(lake_id, exposure, aging_structure_1) %>% 
  count() %>% 
  arrange(lake_id) %>% 
  print(n = nrow(.))


#fit model
fit_blg <- brm(
  length_1 ~ est_age * exposure + sc_lifetime_gdd_anom + (1 | lake_id),
  data = blg_filtered,
  family = gaussian(),
  chains = 4,
  iter = 4000,
  warmup = 1000,
  cores = 4,
  backend = "cmdstanr",
  threads = threading(4), 
  control = list(
    adapt_delta = 0.95,
    max_treedepth = 12))

saveRDS(fit_blg, file.path("G:",
                          "Shared drives",
                          "Hansen Lab",
                          "RESEARCH PROJECTS",
                          "MAISRC Mercury Pathways 53.2",
                          "Growth Analysis",
                          "length_mean_ages_blg.rds"))
rm(blg_plot, blg, blg_filtered)
```

# saved model fits
```{r}
fit_wae <- readRDS(file.path("G:",
                          "Shared drives",
                          "Hansen Lab",
                          "RESEARCH PROJECTS",
                          "MAISRC Mercury Pathways 53.2",
                          "Growth Analysis",
                          "length_mean_ages_wae.rds"))
fit_nop <- readRDS(file.path("G:",
                          "Shared drives",
                          "Hansen Lab",
                          "RESEARCH PROJECTS",
                          "MAISRC Mercury Pathways 53.2",
                          "Growth Analysis",
                          "length_mean_ages_nop.rds"))
fit_blg <- readRDS(file.path("G:",
                          "Shared drives",
                          "Hansen Lab",
                          "RESEARCH PROJECTS",
                          "MAISRC Mercury Pathways 53.2",
                          "Growth Analysis",
                          "length_mean_ages_blg.rds"))
```


# output
```{r}
summary(fit_nop)
plot(conditional_effects(fit_nop))
```

# lake level exposure effect
```{r}
lake_effects <- ranef(fit_wae)$lake_id

lake_exposure_effects <- tibble(
  
  lake_id = rownames(lake_effects[, , 1]),
  
  exposure_effect =
    lake_effects[, "Estimate", "exposurebefore"],
  
  lower =
    lake_effects[, "Q2.5", "exposurebefore"],
  
  upper =
    lake_effects[, "Q97.5", "exposurebefore"]
)

global_effect <- fixef(fit_wae)["exposurebefore", "Estimate"]

lake_exposure_effects <- lake_exposure_effects %>%
  mutate(
    total_effect = exposure_effect + global_effect,
    total_lower  = lower + global_effect,
    total_upper  = upper + global_effect
  )

ggplot(lake_exposure_effects,
       aes(x = reorder(lake_id, total_effect),
           y = total_effect)) +
  
  geom_point() +
  
  geom_errorbar(
    aes(ymin = total_lower,
        ymax = total_upper),
    width = 0
  ) +
  
  geom_hline(yintercept = 0,
             linetype = 2) +
  
  coord_flip() +
  
  labs(
    x = "Lake ID",
    y = "Before - After effect on length (mm)",
    title = "Lake-specific exposure effects"
  )
```


# lake level intercept vis
```{r}
fit_wae %>% 
  spread_draws(r_lake_id[lake_id,Intercept], b_Intercept) %>% 
  mutate(lake_intercept = b_Intercept + r_lake_id) %>% 
  ungroup() %>% 
  ggplot(aes(x = lake_intercept, y = reorder(lake_id, lake_intercept))) +
  geom_vline(xintercept = fixef(fit_wae)[1, 1], color = "#839496", size = 1) +
  geom_vline(xintercept = fixef(fit_wae)[1, 3:4], color = "#839496", linetype = 2) +
  geom_halfeyeh(.width = .5, size = 2/3, fill = "lightblue") +
  labs(x = "Length (inches)",
       y = NULL) +
  theme(panel.grid   = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_text(hjust = 0),
        text = element_text(family = "Ubuntu"))
#value is a hypothetical age-1 (age-2 for blg) fish "before" invasion - we really just want to viz the intercept spread by lake tho
```

