---
title: "temp_prcp_data_nclimgrid"
author: "Denver Link"
date: "2026-06-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Library
```{r}
library(tidyverse)
library(terra)
library(sf)
library(arrow)
library(purrr)
library(RANN)
```

# MN Lakes
```{r}
mn_data <- open_dataset(sources = file.path("F:",
                                            "Shared drives",
                                            "Hansen Lab",
                                            "RESEARCH PROJECTS",
                                            "Fish Survey Data",
                                            "Parquet files",
                                            "mn_update")) 
names(mn_data)

mn_lakes <- mn_data %>% 
  select(lake_id, nhdhr_id, latitude_lake_centroid, longitude_lake_centroid) %>% 
  filter(!is.na(latitude_lake_centroid)) %>% 
  distinct(lake_id, nhdhr_id, latitude_lake_centroid, longitude_lake_centroid) %>% 
  collect()

mn_lakes %>% 
  group_by(nhdhr_id) %>% 
  summarise(n_lat_lon = n_distinct(latitude_lake_centroid, longitude_lake_centroid)) %>% 
  filter(n_lat_lon >1)

mn_lakes %>% 
  filter(nhdhr_id %in% c("nhdhr_120019424", "nhdhr_34123413", "nhdhr_34243896", "nhdhr_80996157", "nhdhr_86272945")) %>% 
  arrange(nhdhr_id, lake_id, latitude_lake_centroid, longitude_lake_centroid)
#mn lakes with a lat/lon with lake id and nhdhr
#we see that some cases have multpule lake ids within an nhdhr - not unexpected and generally "unique" systems 
rm(mn_data)

lakes_vect <- vect(mn_lakes,
                   geom = c("longitude_lake_centroid",
                            "latitude_lake_centroid"),
                   crs = "EPSG:4326")
```

# Any lakes that would return NA values?
```{r}
#let's take a look at just one layer
year <- 1951
month <- 1

url <- paste0(
  "https://www.ncei.noaa.gov/data/nclimgrid-daily/access/grids/",
  year,
  "/ncdd-",
  year,
  sprintf("%02d", month),
  "-grd-scaled.nc"
)

tmp <- tempfile(fileext = ".nc")

download.file(
  url,
  destfile = tmp,
  mode = "wb"
)

s <- sds(tmp)

tmax <- s[["tmax"]]

test <- extract(tmax[[1]],
                lakes_vect)

problem_lakes <- mn_lakes %>% 
  mutate(clim_values = test$tmax_1) %>% 
  filter(is.na(clim_values))

r <- tmax[[1]]
valid_cells <- which(!is.na(values(r)))
valid_xy <- xyFromCell(r, valid_cells)

problem_xy <- as.matrix(
  problem_lakes[, c("longitude_lake_centroid",
                    "latitude_lake_centroid")]
)

nn <- nn2(
  data = valid_xy,
  query = problem_xy,
  k = 1
)

problem_lakes$longitude_clim <-
  valid_xy[nn$nn.idx, 1]

problem_lakes$latitude_clim <-
  valid_xy[nn$nn.idx, 2]

problem_lakes$distance_deg <-
  nn$nn.dists

# now update the mn_lakes product
mn_lakes_fixed <- mn_lakes %>%
  left_join(
    problem_lakes %>%
      select(
        lake_id,
        latitude_clim,
        longitude_clim
      ),
    by = "lake_id"
  ) %>%
  mutate(
    latitude_lake_centroid = coalesce(latitude_clim,
                                      latitude_lake_centroid),
    longitude_lake_centroid = coalesce(longitude_clim,
                                       longitude_lake_centroid)
  ) %>%
  select(-latitude_clim, -longitude_clim)

rm(month, tmp, url, year, s, test, tmax, nn, problem_lakes, problem_xy, r, test, valid_xy, valid_cells)

#now create updated vector 
lakes_vect <- vect(
  mn_lakes_fixed,
  geom = c("longitude_lake_centroid",
           "latitude_lake_centroid"),
  crs = "EPSG:4326"
)
```


# nclim data from URL
```{r}
extract_month_remote <- function(year,
                                 month,
                                 lakes_vect,
                                 lake_ids) {

  url <- paste0(
    "https://www.ncei.noaa.gov/data/nclimgrid-daily/access/grids/",
    year,
    "/ncdd-",
    year,
    sprintf("%02d", month),
    "-grd-scaled.nc"
  )

  tmp <- tempfile(fileext = ".nc")

  on.exit({
    if (file.exists(tmp)) unlink(tmp)
  }, add = TRUE)

  download.file(
    url,
    destfile = tmp,
    mode = "wb",
    quiet = TRUE
  )

  s <- sds(tmp)

  dates <- as.Date(time(s[["tmax"]]))

  make_long <- function(rast_obj, prefix, value_name) {

    extract(rast_obj, lakes_vect) |>
      mutate(lake_id = lake_ids) |>
      select(-ID) |>
      pivot_longer(
        -lake_id,
        names_to = "layer",
        values_to = value_name
      ) |>
      mutate(
        day_num = as.integer(
          gsub(paste0(prefix, "_"), "", layer)
        ),
        date = dates[day_num]
      ) |>
      select(-layer, -day_num)
  }

  tmax_long <- make_long(
    s[["tmax"]],
    "tmax",
    "tmax"
  )

  tmin_long <- make_long(
    s[["tmin"]],
    "tmin",
    "tmin"
  )

  prcp_long <- make_long(
    s[["prcp"]],
    "prcp",
    "prcp"
  )

  tavg_long <- make_long(
    s[["tavg"]],
    "tavg",
    "tavg"
  )

  tmax_long |>
    left_join(tmin_long,
              by = c("lake_id", "date")) |>
    left_join(prcp_long,
              by = c("lake_id", "date")) |>
    left_join(tavg_long,
              by = c("lake_id", "date")) |>
    mutate(
      year = year(date),
      doy = yday(date)
    ) %>% 
    select(lake_id,
           date,
           year, 
           doy,
           tmax,
           tmin,
           tavg,
           prcp)
}

process_year <- function(year,
                         lakes_vect,
                         lake_ids) {

  map_dfr(
    1:12,
    function(m){

      message(
        "Year: ",
        year,
        " Month: ",
        sprintf("%02d", m)
      )

      extract_month_remote(
        year = year,
        month = m,
        lakes_vect = lakes_vect,
        lake_ids = lake_ids
      )
    }
  )
}

save_year <- function(year,
                      lakes_vect,
                      lake_ids,
                      out_dir = "Data/nclim_lake_daily") {

  message("Starting year ", year)

  clim_year <- process_year(
    year = year,
    lakes_vect = lakes_vect,
    lake_ids = lake_ids
  )

  write_dataset(
    clim_year,
    path = out_dir,
    partitioning = "year",
    existing_data_behavior = "delete_matching"
  )

  rm(clim_year)
  gc()

  message("Finished year ", year)
}

#output directory
dir.create(
  "Data/nclim_lake_daily",
  recursive = TRUE,
  showWarnings = FALSE
)

#processes just one year
save_year(
  year = 1951,
  lakes_vect = lakes_vect,
  lake_ids = mn_lakes$lake_id
)

check <- open_dataset(file.path("Data",
                                "nclim_lake_daily"),
                      partitioning = "year") %>% 
  as.tibble()
rm(check)

#########run for all years#####################
purrr::walk(
  2024:2025,
  save_year,
  lakes_vect = lakes_vect,
  lake_ids = mn_lakes$lake_id
)
rm(lakes_vect, mn_lakes)
```

# quick exploration 
```{r}
#open dataset
clim <- open_dataset(file.path("Data",
                     "nclim_lake_daily"),
                     partitioning = "year")
names(clim)

#how many years, min and max years
clim %>% 
  summarise(n_years = n_distinct(year),
            min_year = min(year),
            max_year = max(year)) %>% 
  collect()

#yearly average temp for each lake, what is the trend?
clim %>% 
  group_by(lake_id, year) %>% 
  summarize(
    mean_tavg = mean(tavg, na.rm = TRUE)
  ) %>% 
  collect() %>% 
  ggplot() +
  geom_point(aes(year, mean_tavg), color = "orange", alpha = .5) +
  geom_smooth(aes(year, mean_tavg)) 
#ggsave("yearly_average_temp.jpg", height = 5, width = 5)

clim %>% 
  group_by(year, doy) %>% 
  summarize(
    tavg = mean(tavg, na.rm = TRUE),
    .groups = "drop"
  ) %>% 
  collect() %>% 
  ggplot(
    aes(doy, year, fill = tavg)
  ) +
  geom_tile() +
  scale_fill_viridis_c(
    option = "plasma",
    name = "Temp (°C)"
  ) +
  theme(legend.position = "bottom")
#ggsave("tile_temps.jpg", height = 5, width = 5)

clim %>% 
  filter(lake_id == "1000100") %>% 
  filter(year > 2020 & year < 2026) %>% 
  collect() %>% 
  ggplot(aes(date, tavg)) +
  geom_line(alpha = 0.3) +
  labs(title = "Pine Lake 2021-2025")
#ggsave("one_lake.jpg", height = 5 , width = 5)

#check our weird lakes quick
clim %>% 
  filter(lake_id %in% c("48000200", "4003501", "39000200")) %>% 
  filter(year == 2025) %>% 
  collect() %>% 
  ggplot(aes(date, tavg, color = lake_id)) +
  geom_line(alpha = 0.6) 
```

